---

# This adds pet to the soldier verb list
modifyingUnitClasses:
  - id: soldier
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: spearman
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: archer
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: knight
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: mage
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: merman
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

  - id: villager
    add:
      verbs:
        - pet   # This adds pet to the soldier verbs

...
